server:
  port: 8088

spring:
  main:
    banner-mode: off

  application:
    name: spring-kafka-playground

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      auto-offset-reset: latest

#logging:
#  level:
##    org.apache.kafka: debug
#    org.apache.kafka.clients: WARN
#    org.apache.kafka.common.utils.AppInfoParser: WARN
