server:
  port: 8089

spring:
  main:
    banner-mode: off

  application:
    name: spring-kafka-playground

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      auto-offset-reset: latest

logging:
  level:
#    root: trace
#    org.apache.kafka: debug
    org.apache.kafka: info
#    org.apache.kafka.common.metrics: WARN
#    org.apache.kafka.clients.producer: WARN
#    org.apache.kafka.clients.admin.AdminClientConfig: WARN
#    org.apache.kafka.clients.consumer.ConsumerConfig: WARN
#    org.apache.kafka.common.utils.AppInfoParser: WARN

management:
  endpoints:
    web:
      exposure:
        include: '*'

