server:
  port: 8088

spring:
  main:
    banner-mode: off

  application:
    name: spring-kafka-playground

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      auto-offset-reset: latest

logging:
  level:
#    org.apache.kafka: debug
    org.apache.kafka.clients.producer: WARN
    org.apache.kafka.clients.admin.AdminClientConfig: WARN
    org.apache.kafka.clients.consumer.ConsumerConfig: WARN
    org.apache.kafka.common.utils.AppInfoParser: WARN
